---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: 
 - Launchpad
 - TV
 - Podcasts
 - 'App Store'
 - Safari
 - FaceTime
 - Messages
 - Maps
 - Contacts
 
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

# Variables for creating new ssh key pairs
configure_ssh_key_pair: true
ssh_key_pairs:
 - build
 - gitlab
# Change to yes if you want to override previously created key pairs
force_key_pair_replace: no

configure_sudoers: true
sudoers_custom_config: |
   # Allow users in admin group to use sudo with no password.
   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - awscli
  - bash-completion
  - cask
  - checkov
  - coreutils
  - dos2unix
  - doxygen
  - dmg2img
  - gettext
  - gifsicle
  - git
  - grep
  - gzip
  - helm
  - jq
  - iperf
  - k6
  - libpq
  - libevent
  - sqlite
  - minikube
  - nmap
  - node
  - packer
  - pre-commit
  - pyenv
  - tlc-tk
  - terraform-docs
  - terragrunt
  - terrascan
  - tflint
  - tfsec
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - atom
  - authy
  - bitwarden
  - dbeaver-community
  - docker
  - drawio
  - evernote
  - firefox
  - iterm2
  - keystore-explorer
  - pgadmin4
  - postman
  - rectangle
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant
  - visual-studio-code

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"
