---
downloads: ~/.ansible-downloads/

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: 
 - TV
 - Podcasts
 - 'App Store'
 - Safari
 - FaceTime
 - Messages
 - Maps
 - Contacts
 - Music
 - Photos
 
dockitems_persist: 
 - name: "Launchpad"
   path: "/Applications/Launchpad.app/"
   pos: 2
 - name: "Visual Studio Code"
   path: "/Applications/Visual Studio Code.app/"
   pos: 3
 - name: "Firefox"
   path: "/Applications/Firefox.app/"
   pos: 4
 - name: "Calendar"
   path: "/Applications/Calendar.app/"
   pos: 5
 - name: "Reminders"
   path: "/Applications/Reminders.app/"
   pos: 6
 - name: "Evernote"
   path: "/Applications/Evernote.app/"
   pos: 7
 - name: "Skitch"
   path: "/Applications/Skitch.app/"
   pos: 8
 - name: "System Preferences"
   path: "/Applications/System Preferences.app/"
   pos: 9 
 - name: "draw.io.app"
   path: "/Applications/draw.io.app/"
   pos: 10
 - name: "Slack"
   path: "/Applications/Slack.app/"
   pos: 11
 - name: "Docker"
   path: "/Applications/Docker.app/"
   pos: 12
 - name: "iTerm"
   path: "/Applications/iTerm.app/"
   pos: 13
   
# Variables for creating new ssh key pairs
configure_ssh_key_pair: true
ssh_key_pairs:
 - build
 - gitlab
# Change to yes if you want to override previously created key pairs
force_key_pair_replace: no

configure_dotfiles: true
dotfiles_repo: https://github.com/adamj99/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .osx

configure_sudoers: true
sudoers_custom_config: |
   # Allow users in admin group to use sudo with no password.
   admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - awscli
  - bash-completion
  - cask
  - checkov
  - coreutils
  - dos2unix
  - doxygen
  - dmg2img
  - gettext
  - gifsicle
  - git
  - grep
  - gzip
  - helm
  - jq
  - iperf
  - k6
  - libpq
  - libevent
  - sqlite
  - minikube
  - nmap
  - node
  - packer
  - pre-commit
  - pyenv
  - tcl-tk
  - go
  - k9s
  - wireguard-tools
  - screen
  - gpg
  - massCode
  - terraform-docs
  - kubernetes-cli
  - terragrunt
  - terrascan
  - tflint
  - tfsec
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - atom
  - authy
  - bitwarden
  - dbeaver-community
  - docker
  - drawio
  - evernote
  - firefox
  - iterm2
  - discord
  - google-cloud-sdk
  - zoom
  - 1password
  - keystore-explorer
  - pgadmin4
  - postman
  - rectangle
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant
  - visual-studio-code
  
configure_osx: true
osx_script: "sh ~/.osx --no-restart"

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"
